### ISSUE TITLE
Broken door on cs_estate

### ISSUE THREAD

**Issue by Unargent** [eukara/FreeCS#9] opened 2022-09-06 14:38 UTC
https://user-images.githubusercontent.com/106993968/188663566-8f97fc01-66d4-49de-a2be-c7e3d1463369.mp4

Tested on:
Commits: https://github.com/eukara/freecs/commit/e744c22f40992acdab75b299e7c2140bd4da545468
https://github.com/eukara/freehl/commit/5b9db50f2c40778d36e318ca55a672f6e938b49c
https://github.com/VeraVisions/nuclide/commit/9deb12b68de6485285c81975d20eb93dc9af547b
OS: Debian 11
Backend: SDL2
Render type: OpenGL
Data files: Shareware (from the script)

**Comment by eukara** [comment] 2022-09-06 16:27
It seems to be caused by the func_pushable blocking the way.
I'm working on a workaround.

**Comment by eukara** [comment] 2022-09-12 21:02
Fixed in Nuclide commit https://github.com/VeraVisions/nuclide/commit/b3755bf0a27b9149502fc162f60c78521d050998

**Closed as completed by eukara** 2022-09-12 21:02 UTC
